--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.22.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2023. 02. 26. 11:03:20
-- Server version: 5.5.5-10.4.27-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE recept;

--
-- Drop table `hasznalt`
--
DROP TABLE IF EXISTS hasznalt;

--
-- Drop table `hozzavalo`
--
DROP TABLE IF EXISTS hozzavalo;

--
-- Drop table `etel`
--
DROP TABLE IF EXISTS etel;

--
-- Drop table `kategoria`
--
DROP TABLE IF EXISTS kategoria;

--
-- Set default database
--
USE recept;

--
-- Create table `kategoria`
--
CREATE TABLE kategoria (
  id INT(11) NOT NULL AUTO_INCREMENT,
  nev VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create table `etel`
--
CREATE TABLE etel (
  id INT(11) NOT NULL AUTO_INCREMENT,
  nev VARCHAR(255) NOT NULL,
  kategoriaId INT(11) NOT NULL,
  felirdatum DATE NOT NULL,
  elsodatum DATE DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create foreign key
--
ALTER TABLE etel 
  ADD CONSTRAINT FK_etel_kategoria_id FOREIGN KEY (kategoriaId)
    REFERENCES kategoria(id) ON UPDATE NO ACTION;

--
-- Create table `hozzavalo`
--
CREATE TABLE hozzavalo (
  id INT(11) NOT NULL AUTO_INCREMENT,
  nev VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create table `hasznalt`
--
CREATE TABLE hasznalt (
  id INT(11) NOT NULL AUTO_INCREMENT,
  mennyiseg INT(11) NOT NULL,
  egyseg VARCHAR(255) NOT NULL,
  etelid INT(11) NOT NULL,
  hozzavaloid INT(11) NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

--
-- Create foreign key
--
ALTER TABLE hasznalt 
  ADD CONSTRAINT FK_hasznalt_etel_id FOREIGN KEY (etelid)
    REFERENCES etel(id) ON DELETE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE hasznalt 
  ADD CONSTRAINT FK_hasznalt_hozzavalo_id FOREIGN KEY (hozzavaloid)
    REFERENCES hozzavalo(id) ON DELETE NO ACTION;

-- 
-- Dumping data for table kategoria
--
-- Table recept.kategoria does not contain any data (it is empty)

-- 
-- Dumping data for table hozzavalo
--
-- Table recept.hozzavalo does not contain any data (it is empty)

-- 
-- Dumping data for table etel
--
-- Table recept.etel does not contain any data (it is empty)

-- 
-- Dumping data for table hasznalt
--
-- Table recept.hasznalt does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;